# Sets function directory for 
fpath+=${ZDOTDIR}/functions


zstyle ':autocomplete:*' insert-unambiguous yes
zstyle ':autocomplete:*' widget-style menu-select

# History
export HISTFILE=$ZDOTDIR/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY

# Source plugins
source $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZDOTDIR/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source $ZDOTDIR/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source $ZDOTDIR/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source $ZDOTDIR/plugins/LS_COLORS/lscolors.sh
source $ZDOTDIR/plugins/git/git.plugin.zsh

# There are many zsh-git-prompt repos. This is the one used here - https://github.com/zsh-git-prompt/zsh-git-prompt
source $ZDOTDIR/plugins/zsh-git-prompt/zshrc.sh

# lxd completions
fpath+=${ZDOTDIR}/plugins/lxd-completions-zsh

# Theme
# Main prompt
PROMPT="%{$fg[green]%}$USER@%m %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
# Git dir prompt suffix
PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_super_status)'
# Theme git settings 
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%})"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"

# Source all zshrc configs
if [[ -e $ZDOTDIR/zshrc.d ]]; then
    for i in $(find $ZDOTDIR/zshrc.d -type l,f -name '*.zsh'|sort); do
        source "$i"
    done
fi
